cookie: "exampleCookie1=123; exampleCookie2=456"
companyID: 123
organizationID: 456
secChUa: '"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"'
userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
